### PR TITLE
Add Windows Server 2019 packer builder

### PR DESCRIPTION
**Pull request by pranavmalaviya**
This PR adds a packer builder for Windows Server 2019. It installs the following tools in the AMI.

- Tidal tools (can be used from anywhere using `tidal [command]`)
- Git
- Machine stats (can be used from `C:\machine_stats\windows`)

For more information on how to run machine stats with tidal tools in Windows, have a look the following guides:

- https://guides.tidalmg.com/machine_stats.html#running-the-script
- https://github.com/tidalmigrations/machine_stats/tree/master/windows#usage

To log in to Windows EC2 that you'll create, use the following credentials:

  ```
  Username: Administrator
  Password: Dev12345
  ```

### CODE REVIEW

**Comment by SamDesmondKing** [comment]
Not so much a comment on this PR, but one thing I've noticed is that using the `basic-two-instances` deployment with this PR results in incorrect ports in the security group (SSH 22 instead of RDP 3389). Might be worth having a dedicated `deploy-windows-instance` directory for the future.

**Comment by SamDesmondKing** [comment]
Another thought: can we add `choco install chrome`? I'm finding myself needing another browser during RDP sessions.
https://community.chocolatey.org/packages/GoogleChrome

**Comment by pranavmalaviya** [comment]
> Might be worth having a dedicated `deploy-windows-instance` directory for the future.

I have some questions about adding a new directory. Let's discuss this in syncup today.

**Comment by pranavmalaviya** [comment]
> can we add `choco install chrome`?

Sure, that was a pain point for me too.

**Comment by SamDesmondKing** [comment]
I don't think this is related to this PR but I wanted to log it - weird error spinning this up in `ap-southeast-1` today. Have you seen this before? Worked fine in `ap-northeast-1`.

**Comment by SamDesmondKing** [comment]
Leaving aside the error above, this works great, chrome is installed properly 🚀

**Comment by pranavmalaviya** [comment]
> Have you seen this before?

@SamDesmondKing I was able to reproduce this in `ap-southeast-1` and `ap-northeast-1` regions. I tried forcing git command with more sleep time afterwards, however, I am getting the same `Timed Out` error as you mentioned. I didn't get the OpenSSL error that you got. Interestingly, when I am repeating the same command after logging into the instance it is working well.

I was able to run it successfully in the Canada Central region though.

Although GitHub is running well now, [it was down](https://tidalmg.slack.com/archives/C11NRMQTC/p1647445758704439) yesterday, so maybe it's that. If the error remains the same, I'll work on it in another PR.

**Comment by SamDesmondKing** [comment]
@pranavmalaviya Makes sense, I think that's a good plan. I span up an instance with this successfully too and everything worked great. I think we're good to go.

**Review by SamDesmondKing — APPROVED** [review]
🚀

**Review by jmariomejiap — APPROVED** [review]
Awesome 🚀

**Pull request merged**
